version: '3.9'
name: factum

services:
  postgres:
    image: postgres:16
    container_name: postgres-development
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - postgres_data_development:/var/lib/postgresql/data

volumes:
  postgres_data_development:
